"""Pass 0: Establish an adaptive principles brief for this specific prompt.

Runs a small Haiku call that picks ≤12 load-bearing principles from the
canonical library and produces an interaction contract tailored to the
detected modality/domain. Falls back to a deterministic brief on failure so
the pipeline never dies here. Also attaches the tool-schema registry —
always deterministic, never LLM-derived.
"""

from __future__ import annotations

import logging
from typing import Optional

from core.models import ActivePrinciple, PrinciplesBrief
from core.principles import CANONICAL_PRINCIPLES_TEXT
from core.schema_registry import build_registry_from_json_text

from .llm import HAIKU_MODEL, _cached_block, llm
from .prompts import PRINCIPLES_INSTRUCTION

logger = logging.getLogger(__name__)

MAX_ACTIVE_PRINCIPLES = 12


def _principles_system_blocks() -> list[dict]:
    """System prompt for Pass 0 — canonical library cached, instructions uncached."""
    return [
        _cached_block(
            "<canonical_principles>\n"
            + CANONICAL_PRINCIPLES_TEXT
            + "\n</canonical_principles>"
        ),
        {"type": "text", "text": PRINCIPLES_INSTRUCTION},
    ]


def _fallback_brief(
    prompt_text: str,
    tools_json: Optional[str],
    reason: str = "LLM call failed",
) -> PrinciplesBrief:
    """Deterministic brief when the LLM call fails or returns malformed JSON."""
    low_text = prompt_text.lower()
    low_tools = (tools_json or "").lower()

    if "send_sms" in low_tools or "transfer_call" in low_tools:
        modality: str = "voice"
    elif "phone call" in low_text or "voice" in low_text:
        modality = "voice"
    elif "sms" in low_tools or "text message" in low_text:
        modality = "sms"
    elif "chat" in low_text or "message the user" in low_text:
        modality = "chat"
    else:
        modality = "unknown"

    domain_keywords = [
        ("healthcare", ("patient", "appointment", "provider", "clinic", "medical")),
        ("fintech", ("transaction", "account balance", "fraud", "card", "refund")),
        ("insurance", ("policy", "claim", "coverage", "deductible")),
        ("ecommerce", ("order", "shipment", "return", "cart")),
        ("telecom", ("subscriber", "plan", "outage")),
        ("travel", ("booking", "flight", "itinerary", "reservation")),
    ]
    domain = "unknown"
    signals: list[str] = []
    for tag, kws in domain_keywords:
        if any(kw in low_text for kw in kws):
            if domain == "unknown":
                domain = tag
            signals.append(tag)
    if "schedule" in low_text or "appointment" in low_text:
        signals.append("scheduling")

    defaults = [
        ("STRUCT-01", "Static/variable separation is a general cacheability concern"),
        ("ROLE-01", "Scope and out-of-scope must be explicit for any agent"),
        ("TOOL-01", "Check for blanket 'always use' tool-use wording"),
        ("TOOL-04", "Parameter formats in prose must match tool schemas"),
        ("TOOL-06", "Tool failure handling is commonly missing"),
        ("STYLE-01", "Modality-appropriate response length"),
        ("GUARD-01", "One targeted follow-up on ambiguity"),
        ("SAFE-01", "Atomicity for multi-step side-effect operations"),
    ]
    if domain == "healthcare":
        defaults.extend([
            ("ELIG-01", "Eligibility pre-checks before slot offers"),
            ("CONTENT-01", "Notifications must carry the 5-Ws"),
        ])
    active = [ActivePrinciple(id=pid, reason=r) for pid, r in defaults]

    return PrinciplesBrief(
        modality=modality,  # type: ignore[arg-type]
        domain=domain,
        domain_signals=list(dict.fromkeys(signals)),
        active_principles=active,
        interaction_contract=(
            f"{modality.title()}-modality {domain} agent. Keep replies concise "
            "and on-task, ask one follow-up at a time when information is "
            "missing, confirm key fields before irreversible actions, and "
            "avoid dumping policy text to the caller."
        ),
        structure_notes=(
            f"Principles brief generated by deterministic fallback "
            f"(reason: {reason}). Downstream passes evaluate against the "
            "default active-principles set."
        ),
    )


def establish_principles(
    prompt_text: str, tools_json: Optional[str] = None
) -> PrinciplesBrief:
    """Pass 0 — produce an adaptive quality lens for this specific prompt."""
    registry = build_registry_from_json_text(tools_json)

    user_content = f"<prompt>\n{prompt_text}\n</prompt>"
    if tools_json:
        user_content += f"\n\n<tool_definitions>\n{tools_json}\n</tool_definitions>"
    if registry:
        user_content += f"\n\n{registry}"

    try:
        brief = llm.call_json(
            _principles_system_blocks(),
            user_content,
            PrinciplesBrief,
            max_tokens=4096,
            model=HAIKU_MODEL,
        )
    except Exception as err:
        logger.warning("Pass 0 LLM call failed, using deterministic fallback: %s", err)
        brief = _fallback_brief(prompt_text, tools_json, reason=str(err)[:80])

    if len(brief.active_principles) > MAX_ACTIVE_PRINCIPLES:
        brief.active_principles = brief.active_principles[:MAX_ACTIVE_PRINCIPLES]

    brief.tool_schema_registry = registry
    return brief


def format_brief_for_passes(brief: Optional[PrinciplesBrief]) -> str:
    """Serialise a brief into the XML block injected into downstream user content."""
    if brief is None:
        return ""
    active = "\n".join(
        f"- {p.id}: {p.reason}" for p in brief.active_principles
    )
    block = (
        "<principles_brief>\n"
        f"modality: {brief.modality}\n"
        f"domain: {brief.domain}\n"
        f"domain_signals: {', '.join(brief.domain_signals) or '(none)'}\n"
        f"interaction_contract: {brief.interaction_contract}\n"
        f"structure_notes: {brief.structure_notes}\n"
        "active_principles:\n"
        f"{active}\n"
        "</principles_brief>"
    )
    if brief.tool_schema_registry:
        block += "\n\n" + brief.tool_schema_registry
    return block
